### ISSUE TITLE
can u tell me how  this data is put into DATO

### ISSUE THREAD

**Issue by clockshark** [datocms/jekyll-example#1]
We cannot find a way to put the data in DATO to get it out how you describe it here.

**Comment by matjack1** [comment]
sorry @clockshark I've missed this issue before :(

If you want to have more info, please have a look at our documentation: https://www.datocms.com/docs/static-generators/jekyll

Or ask this kind of open ended questions in our Community: https://community.datocms.com/

**Comment by matjack1** [comment]
Oh and this project needs updating, please check this other Jekyll example that is up to date: https://github.com/datocms/jekyll-portfolio
